---
- name: Clone GitHub repository
  hosts: your_target_host
  gather_facts: no
  tasks:
    - name: Install git
      become: yes
      package:
        name: git
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/GRajashekarreddy/GitHub-Actions-Zero-to-Hero.git
        dest: /path/to/clone/the/repository
        update: yes # Optional, updates the repository if it already exists
